language: php

sudo: false

env:
  global:
    - COMPOSER_NO_INTERACTION="1"

matrix:
    include:
      - php: "7.0"
      - php: "7.1"
      - php: "7.2"
      - php: "7.3"
        env: WITH_CS="true"

      - php: "7.0"
        env: LOWER_CONSTRAINTS="true"
      - php: "7.1"
        env: LOWER_CONSTRAINTS="true"
      - php: "7.2"
        env: LOWER_CONSTRAINTS="true"
      - php: "7.3"
        env: LOWER_CONSTRAINTS="true"

cache:
    directories:
      - $HOME/.composer/cache

install:
    - IFS=$'\n'; COMMIT_SCA_FILES=($(git diff --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT_RANGE}")); unset IFS

before_script:
    - phpenv config-rm xdebug.ini || true
    - if [[ "$LOWER_CONSTRAINTS" == "true" ]]; then bin/update-constraints-to-lowest.php; fi
    - bash -c "composer update"

script:
    - bin/phpunit
    - if [[ "$WITH_CS" == "true" ]]; then bin/paysera-php-cs-fixer fix --config=.php_cs -v --dry-run --stop-on-violation --using-cache=no --path-mode=intersection "${COMMIT_SCA_FILES[@]}"; fi
